export const INTEGRATION = [
  { id: 1, icon: "logos:google-drive", name: "Google Drive" },
  { id: 2, icon: "logos:slack", name: "Slack" },
  { id: 3, icon: "logos:hubspot", name: "HubSpot" },
  { id: 4, icon: "logos:mailchimp-freddie", name: "MailChimp" },
  { id: 5, icon: "logos:google-gmail", name: "Gmail" },
  { id: 6, icon: "logos:twitter", name: "X/Twitter" },
  { id: 7, icon: "logos:twilio", name: "Twilio" },
  { id: 8, icon: "logos:whatsapp-icon", name: "WhatsApp" },
  { id: 9, icon: "logos:dropbox", name: "Dropbox" },
  { id: 10, icon: "logos:youtube-icon", name: "YouTube" },
  { id: 11, icon: "logos:postgresql", name: "PostgreSQL" },
  { id: 12, icon: "logos:notion", name: "Notion" },
  { id: 13, icon: "logos:github", name: "GitHub" },
  { id: 14, icon: "logos:jira", name: "Jira" },
  { id: 15, icon: "logos:zoho", name: "Zoho" },
  { id: 17, icon: "logos:ibm", name: "IBM App Connect" },
  { id: 18, icon: "logos:looker", name: "Looker" },
  { id: 19, icon: "logos:facebook", name: "Facebook" },
  { id: 20, icon: "logos:discord-icon", name: "Discord" },
  { id: 21, icon: "logos:twilio", name: "Twilio" },
  { id: 22, icon: "devicon:linkedin", name: "LinkedIn" },
  { id: 23, icon: "logos:zapier", name: "Zapier" },
  { id: 24, icon: "logos:apple", name: "Apple" },
  { id: 25, icon: "vscode-icons:file-type-outlook", name: "Outlook" },
];
