export const INTEGRATION = [
  { id: 1, icon: "logos:slack", name: "Slack" },
  { id: 2, icon: "logos:discord", name: "Discord" },
  { id: 3, icon: "logos:jira", name: "Jira" },
  { id: 4, icon: "logos:github", name: "GitHub" },
  { id: 5, icon: "logos:figma", name: "Figma" },
  { id: 6, icon: "logos:notion", name: "Notion" },
  { id: 7, icon: "logos:google-drive", name: "Google Drive" },
  { id: 8, icon: "logos:trello", name: "Trello" },
  { id: 9, icon: "logos:hubspot", name: "HubSpot" },
  { id: 10, icon: "logos:asana", name: "Asana" },
  { id: 11, icon: "logos:airtable", name: "Airtable" },
  { id: 12, icon: "logos:intercom", name: "Intercom" },
  { id: 13, icon: "logos:google-analytics", name: "Google Analytics" },
  { id: 14, icon: "logos:google-ads", name: "Google Ads" },
  { id: 15, icon: "logos:google-tag-manager", name: "Google Tag Manager" },
  { id: 16, icon: "logos:google-adsense", name: "Google AdSense" },
  { id: 17, icon: "logos:dropbox", name: "Dropbox" },
  { id: 18, icon: "logos:zoom", name: "Zoom" },
  { id: 19, icon: "logos:monday", name: "Monday.com" },
  { id: 20, icon: "logos:shopify", name: "Shopify" },
  { id: 21, icon: "logos:wix", name: "Wix" },
  { id: 23, icon: "logos:webflow", name: "Webflow" },
  { id: 24, icon: "logos:stripe", name: "Stripe" },
  { id: 25, icon: "logos:paypal", name: "PayPal" },
];
